### PR TITLE
Local changes

### PR DESCRIPTION
**Pull request by miamiroy**
Move classes into a package. 
Added renew method.

### CODE REVIEW

**Comment by jhaals** [comment]
This is great improvements @rojocoding! Why did you close the PR?

**Comment by miamiroy** [comment]
Hi Johan, 

I apologized I was not monitoring this email account for a while. I think I pull it back because there someone else before me with some similar changes. I can review on the am EST time if you guys have not mada changes and resent PR. 

Thanks for reaching back.

**Comment by jhaals** [comment]
That would be great, thanks a lot 👍

**Comment by miamiroy** [comment]
Hi Johan, 

Reopen PR in case you want to merge changes.

**Pull request merged**
